#
# repository of converted observations
cookedDir: /var/mellow/mastodon/cooked
#
# repository of freshly collected observations
freshDir: /var/mellow/mastodon/fresh
#
# peaker files
peakerDir: /var/mellow/mastodon/peaker
#
# processed artifacts
processedDir: /var/mellow/mastodon/processed
#
# collection antenna
#antenna: discone1
antenna: discone2
#antenna: whip
#
# collection host location
#site: anderson1
#site: development1
site: vallejo1
#
# project
project: big-search01
#
# receiver
receiver: rtl-sdr-5
#receiver: rtl-sdr-14
#
peakerAlgorithm: 1
#
